version: '3'
services:
  meilisearch:
      container_name: threat-hawk-meilisearch
      image: getmeili/meilisearch:latest
      environment:
        - MEILI_ENV=development
      ports:
        - "7700:7700"
      networks:
        - threat_hawk_network
      volumes:
        - ./data.ms:/data.ms
      restart: unless-stopped
  threat-hawk-enrichment:
    build: .
    container_name: threat-hawk-enrichment
    environment:
      - MEILI_URL=http://threat-hawk-meilisearch:7700
      - ENCODING_URL=http://threat-hawk-encoding:8000
    restart: always
    ports:
      - "8000:8000"
    networks:
      - threat_hawk_network


# defined my own network here where the db n this is connected
networks:
  threat_hawk_network:
    external: true